### ISSUE TITLE
Drag and drop functionality not working in Internet Explorer (IE 11) browser

### ISSUE THREAD

**Issue by ksck23** [ColdDay/vue-drag-tree-table#1]
Hi,

Thanks for this plugin which is very useful for our requirement. But i saw an issue with IE browser where drag and drop is not working. Can you please help with the fix or have any plan to fix in the future ?

**Comment by ColdDay** [comment]
Thank you for your advice. I will optimize the problem in the next version.

**Comment by ColdDay** [comment]
Hi,The IE problem has been solved. You can try it.
